export enum AppStates {
	READY = 'READY',
	MOUNTED = 'MOUNTED',
	LOADING = 'LOADING',
	INITAILIZED = 'INITAILIZED',
	CUTSCENE = 'CUTSCENE',
	MENU = 'MENU',
	RUNNING = 'RUNNING',
	EXITING = 'EXITING'
}
